import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Fheader from "./components/headers/Fheader";
import Mheader from "./components/headers/Mheader";
import Navbar from "./components/headers/Navbar";
const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Fheader />
        <Mheader />
        <Navbar />
        {children}
      </body>
    </html>
  );
}
